seperation of files, code optimization
secrashi/Connect-Intellect pull request #4
Opened 2021-10-03 06:55 UTC by sohan2410

Made the following changes

- Added server/.env.example, client/.env.example : to get idea what all env's to be added
- Added client/scr/backend.js : it will return backend api based on development or production mode
- Added client/src/utils/fetchData.js : get, post, put, patch, delete function which can be used anywhere in the app
- modified server/index.js : modified app.use(cors()) for crud operations 
- modified server/package.json : moved nodemon package in devDependencies

ps: expecting medium/hard tag

2021-10-08 07:28 UTC, sakshi-dhamija requested changes
Please revert back all the format changes, space deletions, and `''` to `""` conversions etc. Then I'll review the other part of the PR. Also, Please focus on only one issue per PR.

2021-10-08 07:28 UTC, sakshi-dhamija commented on .gitignore
> +client/.env
We do not have .env file in the client so this is unnecsseary.

2021-10-08 07:28 UTC, sakshi-dhamija commented on client/src/App.jsx
> +};
I have added spacing to make it more neat and organized. Also `''` these work just fine, and complete the purpose, so there is no need to change them.

2021-10-08 07:28 UTC, sakshi-dhamija commented on server/controllers/auth.js
> +    ads;
ads is an unnecessary variable that was added mistakenly, you can remove it.

2021-10-08 07:28 UTC, sakshi-dhamija commented on server/package.json
> +    "nodemon": "^2.0.13"
Can you explain to me, what is the requirement for doing so?

2021-10-18 09:57 UTC, sohan2410 commented on server/package.json
> +    "nodemon": "^2.0.13"
Since `nodemon` is used only for development purpose, we don't want it to be installed at production mode

2021-10-18 09:57 UTC, sohan2410 commented on .gitignore
> +client/.env
We do have .env in frontend
`REACT_APP_STREAM_API_KEY` : which is stream api key
`REACT_APP_BACKEND` : URL of deployed backend website
`REACT_APP_BACKEND_LOCAL` : URL of localhost backend
I've kept `REACT_APP_BACKEND `and `REACT_APP_BACKEND_LOCAL `separately as we don't have to every time change back-end API while in production or development mode

2021-10-18 09:57 UTC, sohan2410 commented on client/src/App.jsx
> +};
Regarding the tabWidth and singleQuote, prettier have modified so I'll be creating a prettier config file so that all the documents are formatted according to the options provided in config file.

2021-10-26 18:39 UTC, sakshi-dhamija commented
Hello, @sohan2410 edit the readme.MD file and add the requirement of other keys/ secrets on the client-side so that installation and setup are beginner-friendly. Also, go through the changes requested in order to merge this pr.

2021-10-27 16:31 UTC, merged